import type { DashboardData } from "./types.ts";

const now = new Date();
const hoursAgo = (hours: number) => new Date(now.getTime() - hours * 3_600_000).toISOString();

export const sampleData: DashboardData = {
  targets: [
    {
      id: "job-northstar",
      companyId: "company-northstar",
      companyName: "Northstar Labs",
      title: "AI Software Engineer",
      externalId: "NS-AI-204",
      location: "Singapore / Remote APAC",
      country: "SG",
      workMode: "remote",
      remoteScope: "apac",
      sponsorship: "yes",
      seniority: "mid",
      salary: "SGD 120k - 160k",
      postedAt: hoursAgo(20),
      firstSeenAt: hoursAgo(8),
      lastSeenAt: hoursAgo(1),
      sourceUrl: "https://northstar.example/careers/ns-ai-204",
      applyUrl: "https://northstar.example/careers/ns-ai-204/apply",
      status: "targeted",
      score: 94,
      scoreBreakdown: { roleFit: 100, seniority: 92, modeVisa: 96, freshness: 88, skillOverlapCv: 94 },
      aiEvidence: [
        { quote: "AI Software Engineer", context: "title" },
        { quote: "Build and deploy LLM-powered product features with a product engineering team.", context: "job description" },
      ],
      jdText: "We are looking for an AI Software Engineer to build and deploy LLM-powered product features with a product engineering team. You will work across TypeScript services, Python model integration, evaluation, and production observability. Working language is English. This role is open to candidates in APAC and sponsorship is available for the right candidate.",
      contacts: [
        { id: "contact-1", name: "Maya Chen", role: "Talent Partner", email: "maya.chen@northstar.example", kind: "public", sourceUrl: "https://northstar.example/careers/ns-ai-204", sourceQuote: "Questions? Contact Maya Chen at maya.chen@northstar.example.", jevVerdict: "verified", invalidAt: null },
      ],
      decisions: [
        { id: "decision-1", decisionId: "role_relevance", subjectType: "job", subjectId: "job-northstar", verdict: "relevant", confidence: 0.98, input: "AI Software Engineer; Build and deploy LLM-powered product features", createdAt: hoursAgo(2) },
        { id: "decision-2", decisionId: "language_fit", subjectType: "job", subjectId: "job-northstar", verdict: "english_working_language", confidence: 0.97, input: "Working language is English.", createdAt: hoursAgo(2) },
      ],
    },
    {
      id: "job-orbit",
      companyId: "company-orbit",
      companyName: "Orbit Commerce",
      title: "Fullstack Engineer, AI Products",
      externalId: "ORB-7781",
      location: "London, UK / Hybrid",
      country: "UK",
      workMode: "hybrid",
      remoteScope: "restricted",
      sponsorship: "unknown",
      seniority: "early",
      salary: "GBP 70k - 90k",
      postedAt: hoursAgo(32),
      firstSeenAt: hoursAgo(29),
      lastSeenAt: hoursAgo(2),
      sourceUrl: "https://orbit.example/jobs/7781",
      applyUrl: "https://orbit.example/jobs/7781/apply",
      status: "judged",
      score: 82,
      scoreBreakdown: { roleFit: 88, seniority: 86, modeVisa: 60, freshness: 82, skillOverlapCv: 91 },
      aiEvidence: [
        { quote: "Fullstack Engineer, AI Products", context: "title" },
        { quote: "Ship AI-assisted workflows and agentic coding experiences.", context: "job description" },
      ],
      jdText: "Ship AI-assisted workflows and agentic coding experiences across our commerce platform. You will partner with product and design to build reliable fullstack features. The working language is English.",
      contacts: [],
      decisions: [
        { id: "decision-3", decisionId: "remote_scope", subjectType: "job", subjectId: "job-orbit", verdict: "remote_restricted", confidence: 0.88, input: "London, UK / Hybrid", createdAt: hoursAgo(3) },
      ],
    },
    {
      id: "job-solace",
      companyId: "company-solace",
      companyName: "Solace Health",
      title: "Applied AI Engineer",
      externalId: "SH-AI-119",
      location: "Toronto, Canada / Remote",
      country: "CA",
      workMode: "remote",
      remoteScope: "global",
      sponsorship: "no",
      seniority: "senior",
      salary: "CAD 135k - 170k",
      postedAt: hoursAgo(48),
      firstSeenAt: hoursAgo(45),
      lastSeenAt: hoursAgo(3),
      sourceUrl: "https://solace.example/jobs/applied-ai",
      applyUrl: "https://solace.example/jobs/applied-ai/apply",
      status: "targeted",
      score: 76,
      scoreBreakdown: { roleFit: 96, seniority: 70, modeVisa: 48, freshness: 70, skillOverlapCv: 96 },
      aiEvidence: [
        { quote: "Applied AI Engineer", context: "title" },
        { quote: "Deploy production model systems and LLM evaluation pipelines.", context: "job description" },
      ],
      jdText: "Deploy production model systems and LLM evaluation pipelines for healthcare workflows. This is a remote role for candidates authorized to work in Canada. The working language is English.",
      contacts: [
        { id: "contact-2", name: "Jordan Lee", role: "Engineering Recruiter", email: "jordan.lee@solace.example", kind: "recruiter_search", sourceUrl: "https://solace.example/team/jordan-lee", sourceQuote: "Jordan Lee, Engineering Recruiter.", jevVerdict: "verified", invalidAt: null },
      ],
      decisions: [
        { id: "decision-4", decisionId: "sponsorship", subjectType: "job", subjectId: "job-solace", verdict: "no", confidence: 0.96, input: "candidates authorized to work in Canada", createdAt: hoursAgo(4) },
      ],
    },
  ],
  outreach: [
    { id: "outreach-1", jobId: "job-northstar", jobTitle: "AI Software Engineer", companyName: "Northstar Labs", kind: "initial", subject: "AI Software Engineer / NS-AI-204: production LLM systems", body: "Hello Maya,\n\nI am reaching out about Northstar Labs' AI Software Engineer role. The focus on deploying LLM-powered product features is closely aligned with my work building production AI services across TypeScript and Python.\n\nI would welcome a 15 minute conversation about the role.\n\nBest,\nBrian", cvVariant: "AI Engineer", status: "draft", scheduledFor: null, sentAt: null, gmailThreadId: null, replyClass: null, contactEmail: "maya.chen@northstar.example" },
    { id: "outreach-2", jobId: "job-orbit", jobTitle: "Fullstack Engineer, AI Products", companyName: "Orbit Commerce", kind: "initial", subject: "Fullstack Engineer, AI Products / ORB-7781", body: "Hello Orbit team,\n\nI am interested in the Fullstack Engineer, AI Products role and the opportunity to ship AI-assisted workflows. My background combines product engineering with LLM feature delivery.\n\nCould we schedule 15 minutes to discuss the team?\n\nBest,\nBrian", cvVariant: "AI Fullstack", status: "scheduled", scheduledFor: new Date(now.getTime() + 86_400_000).toISOString(), sentAt: null, gmailThreadId: null, replyClass: null, contactEmail: "hiring@orbit.example" },
    { id: "outreach-3", jobId: "job-solace", jobTitle: "Applied AI Engineer", companyName: "Solace Health", kind: "followup", subject: "Following up: Applied AI Engineer / SH-AI-119", body: "Hello Jordan,\n\nFollowing up on my note about the Applied AI Engineer role. I would be glad to share more about production model systems and LLM evaluation work.\n\nBest,\nBrian", cvVariant: "AI Engineer", status: "followup_due", scheduledFor: hoursAgo(-3), sentAt: hoursAgo(-6), gmailThreadId: "thread-1", replyClass: null, contactEmail: "jordan.lee@solace.example" },
    { id: "outreach-4", jobId: "job-northstar", jobTitle: "AI Software Engineer", companyName: "Northstar Labs", kind: "initial", subject: "AI Software Engineer / NS-AI-204", body: "Hello,\n\nI am applying for the AI Software Engineer role.\n\nBest,\nBrian", cvVariant: "AI Engineer", status: "sent", scheduledFor: hoursAgo(7), sentAt: hoursAgo(7), gmailThreadId: "thread-2", replyClass: null, contactEmail: "maya.chen@northstar.example" },
    { id: "outreach-5", jobId: "job-orbit", jobTitle: "Fullstack Engineer, AI Products", companyName: "Orbit Commerce", kind: "initial", subject: "Fullstack Engineer, AI Products / ORB-7781", body: "Hello,\n\nI am applying for the Fullstack Engineer, AI Products role.\n\nBest,\nBrian", cvVariant: "AI Fullstack", status: "replied", scheduledFor: hoursAgo(20), sentAt: hoursAgo(20), gmailThreadId: "thread-3", replyClass: "positive", contactEmail: "hiring@orbit.example" },
  ],
  companies: [
    { id: "company-northstar", name: "Northstar Labs", domain: "northstar.example", country: "SG", tier: "T1", sourceCount: 3, health: "ok", lastRunAt: hoursAgo(1), nextDueAt: hoursAgo(-1) },
    { id: "company-orbit", name: "Orbit Commerce", domain: "orbit.example", country: "UK", tier: "T2", sourceCount: 2, health: "failing", lastRunAt: hoursAgo(2), nextDueAt: hoursAgo(-1) },
    { id: "company-solace", name: "Solace Health", domain: "solace.example", country: "CA", tier: "T1", sourceCount: 2, health: "ok", lastRunAt: hoursAgo(3), nextDueAt: hoursAgo(-2) },
  ],
  sources: [
    { id: "source-greenhouse", name: "Greenhouse JSON API", kind: "ats", countries: ["global"], roles: ["job_record"], method: "json_api", trust: "official", status: "active", yieldStats: { relevantPer100: 18, duplicateRatio: 22, failureRate: 4, lastFoundAt: hoursAgo(1) }, configUrl: "https://boards-api.greenhouse.io/v1/boards" },
    { id: "source-mcf", name: "MyCareersFuture", kind: "gov_portal", countries: ["SG"], roles: ["job_record", "discovery"], method: "json_api", trust: "public_listing", status: "active", yieldStats: { relevantPer100: 11, duplicateRatio: 34, failureRate: 2, lastFoundAt: hoursAgo(2) }, configUrl: "https://www.mycareersfuture.gov.sg" },
    { id: "source-join", name: "JOIN ATS", kind: "ats", countries: ["DE"], roles: ["job_record"], method: "html_selector", trust: "official", status: "candidate", yieldStats: { relevantPer100: 7, duplicateRatio: 48, failureRate: 9, lastFoundAt: hoursAgo(15) }, configUrl: "https://join.com" },
    { id: "source-brave", name: "Country discovery dorks", kind: "search_dork", countries: ["global"], roles: ["discovery"], method: "custom_adapter", trust: "derived", status: "active", yieldStats: { relevantPer100: 5, duplicateRatio: 72, failureRate: 8, lastFoundAt: hoursAgo(4) }, configUrl: "https://search.brave.com" },
  ],
  settings: {
    name: "Ade Febrian",
    email: "ade.febrian@example.com",
    location: "Indonesia (GMT+7)",
    summary: "AI software engineer building reliable product-facing LLM systems, fullstack applications, and evaluation workflows.",
    skills: ["TypeScript", "React", "Node.js", "Python", "LLM systems", "Postgres"],
    availability: "Available with 30 days notice",
    cvVariants: [
      { id: "cv-ai", name: "AI Engineer", roleType: "AI Engineer", fileName: "CV_Ade_Febrian_AI_Engineer.pdf" },
      { id: "cv-fullstack", name: "AI Fullstack", roleType: "Fullstack", fileName: "CV_Ade_Febrian_AI_Fullstack.pdf" },
    ],
    countries: [
      { code: "SG", name: "Singapore", weight: 100 },
      { code: "AU", name: "Australia", weight: 85 },
      { code: "NZ", name: "New Zealand", weight: 82 },
      { code: "US", name: "United States", weight: 78 },
      { code: "UK", name: "United Kingdom", weight: 88 },
      { code: "CA", name: "Canada", weight: 84 },
      { code: "CH", name: "Switzerland", weight: 74 },
      { code: "DE", name: "Germany", weight: 80 },
      { code: "AE", name: "United Arab Emirates", weight: 70 },
      { code: "QA", name: "Qatar", weight: 66 },
      { code: "SA", name: "Saudi Arabia", weight: 62 },
    ],
    scoreWeights: { roleFit: 35, seniority: 20, modeVisa: 25, freshness: 10, skillOverlapCv: 10 },
    sender: "Ade Febrian <ade.febrian@example.com>",
    dailyCap: 20,
    llmBudgetUsd: 30,
  },
  status: {
    lastRunT1: hoursAgo(1),
    lastRunT2: hoursAgo(3),
    lastRunT3: hoursAgo(23),
    queueDepth: 14,
    llmSpendUsd: 8.42,
    blockedSources: 2,
  },
};
